services:
  frontend:
    container_name: frontend-c
    build:
      context: ./frontend
      dockerfile: Dockerfile
    environment:
      - MONGODB_URI=${MONGODB_URI}
      - NODE_ENV=${NODE_ENV}
      - CLERK_SECRET_KEY=${CLERK_SECRET_KEY}
      - NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY=${NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY}
      - NEXT_PUBLIC_CLERK_SIGN_IN_URL=${NEXT_PUBLIC_CLERK_SIGN_IN_URL}
      - NEXT_PUBLIC_CLERK_SIGN_UP_URL=${NEXT_PUBLIC_CLERK_SIGN_UP_URL}
    ports:
      - 8000:8000
    volumes:
      - ./frontend:/app
      - frontend-v-node-modules:/app/node_modules
    depends_on:
      - database

  database:
    container_name: database-c
    image: mongo:latest
    build:
      context: ./database
      dockerfile: Dockerfile
    ports:
      - 27017:27017
    volumes:
      - database-v:/data/db
      - ./database/init.js:/docker-entrypoint-initdb.d/init.js

  ngrok:
    container_name: ngrok-c
    image: ngrok/ngrok:latest
    command:
      - "http"
      - "http://host.docker.internal:8000"
      - "--domain=better-liberal-adder.ngrok-free.app"
    environment:
      - NGROK_AUTHTOKEN= ${NGROK_AUTHTOKEN}
    ports:
      - 4040:4040

volumes:
  frontend-v-node-modules:
    name: "frontend-v-node-modules"
  database-v:
    name: "database-v"
