name: Build and Test
on:
  push:
    branches:
      - main
      - ci-cd-pipeline
  pull_request:
    branches:
      - main
      - ci-cd-pipeline

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        working-directory: frontend
        run: npm install --legacy-peer-deps

      - name: Install Docker using Docker's official script
        run: |
          curl -fsSL https://get.docker.com -o get-docker.sh
          sudo sh get-docker.sh

      - name: Install Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/v2.3.3/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          docker-compose --version

      - name: Run docker-compose
        run: docker-compose up -d

      - name: Run Jest tests
        run: npm test

      - name: Run Cypress tests
        working-directory: frontend
        run: npx cypress run

      - name: Run Postman tests
        run: |
          npm install -g newman
          newman run postman/Foodable.postman_collection.json --environment postman/Foodable.postman_environment.json

      - name: Shut down Docker Compose
        run: docker-compose down
